const mongoose =require("mongoose")
const schena=new mongoose.Schema(
{
    userName:
    {
        type:String,
        required:true,
        unique:true
    },
    email:
    {
        type:String,
        required:true,
        unique:true
    },
    password:
    {
        type:String,
        required:true,
        unique:false
    },
    createdAt:
    {
        type:Date,
        default:Date.now
    },
    updataAt:
    {
        type:Date,
        default:Date.now
    },
    personType:
    {
        type:String,
        default:"user"
    }    
}
)
const User=mongoose.model("user",schena)
module.exports=User